#!/bin/bash

self=$0

show_help () {
    cat  << END_HELP

Usage: $self [-i] [-j NETWORK_ID] [-u|-d]

Options:
    -i - install all required packages
    -j NETWORK_ID - join zerotier network with specified id

    -u - make network channel up
    -d - make network channel down

Note: requires root privileges for any option!

END_HELP
}


while getopts "ij:udh" opt; do case $opt in
    i)
pacman -S archlinux-keyring --noconfirm
        pacman -Syu zerotier-one openssh --noconfirm
        ;;

    j)

        NETWORK_ID=$OPTARG
            if [ -z "$NETWORK_ID" ]; then
                echo "Error: Option -c requires a non-empty argument." >&2
                exit 1
            fi
zerotier-cli join $NETWORK_ID
        ;;

    u)
        systemctl start zerotier-one.service
        systemctl start sshd.service
        ;;

    d)
        systemctl stop zerotier-one.service
        systemctl stop sshd.service
        ;;

    h)  show_help
        ;;

    *)  echo "Error in parsing options" >&2
        exit 1
        ;;
  esac
done

# Check if no options were provided
if [ $OPTIND -eq 1 ]; then
    echo "Error: No options provided." >&2
    show_help
    exit 1
fi
